/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CreatePostDto,
  Post,
  ResponsePostDto,
  SearchPostDto,
} from "../models";
import {
  CreatePostDtoFromJSON,
  CreatePostDtoToJSON,
  PostFromJSON,
  PostToJSON,
  ResponsePostDtoFromJSON,
  ResponsePostDtoToJSON,
  SearchPostDtoFromJSON,
  SearchPostDtoToJSON,
} from "../models";

export interface PostsControllerCreateRequest {
  createPostDto: CreatePostDto;
}

export interface PostsControllerFindAllRequest {
  searchPostDto: SearchPostDto;
}

export interface PostsControllerRemoveRequest {
  id: string;
}

export interface PostsControllerUpdateRequest {
  id: string;
  createPostDto: CreatePostDto;
}

/**
 *
 */
export class PostsApi extends runtime.BaseAPI {
  /**
   * Post creation
   */
  async postsControllerCreateRaw(
    requestParameters: PostsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Post>> {
    if (
      requestParameters.createPostDto === null ||
      requestParameters.createPostDto === undefined
    ) {
      throw new runtime.RequiredError(
        "createPostDto",
        "Required parameter requestParameters.createPostDto was null or undefined when calling postsControllerCreate."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/posts`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreatePostDtoToJSON(requestParameters.createPostDto),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PostFromJSON(jsonValue)
    );
  }

  /**
   * Post creation
   */
  async postsControllerCreate(
    requestParameters: PostsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Post> {
    const response = await this.postsControllerCreateRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * All Posts getting
   */
  async postsControllerFindAllRaw(
    requestParameters: PostsControllerFindAllRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ResponsePostDto>> {
    if (
      requestParameters.searchPostDto === null ||
      requestParameters.searchPostDto === undefined
    ) {
      throw new runtime.RequiredError(
        "searchPostDto",
        "Required parameter requestParameters.searchPostDto was null or undefined when calling postsControllerFindAll."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/posts/search`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SearchPostDtoToJSON(requestParameters.searchPostDto),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ResponsePostDtoFromJSON(jsonValue)
    );
  }

  /**
   * All Posts getting
   */
  async postsControllerFindAll(
    requestParameters: PostsControllerFindAllRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ResponsePostDto> {
    const response = await this.postsControllerFindAllRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Delete Post by id
   */
  async postsControllerRemoveRaw(
    requestParameters: PostsControllerRemoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling postsControllerRemove."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/posts/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete Post by id
   */
  async postsControllerRemove(
    requestParameters: PostsControllerRemoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.postsControllerRemoveRaw(requestParameters, initOverrides);
  }

  /**
   */
  async postsControllerUpdateRaw(
    requestParameters: PostsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling postsControllerUpdate."
      );
    }

    if (
      requestParameters.createPostDto === null ||
      requestParameters.createPostDto === undefined
    ) {
      throw new runtime.RequiredError(
        "createPostDto",
        "Required parameter requestParameters.createPostDto was null or undefined when calling postsControllerUpdate."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/posts/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: CreatePostDtoToJSON(requestParameters.createPostDto),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async postsControllerUpdate(
    requestParameters: PostsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.postsControllerUpdateRaw(requestParameters, initOverrides);
  }
}
