/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
  /**
   * Title
   * @type {string}
   * @memberof CreatePostDto
   */
  title: string;
  /**
   * Description
   * @type {string}
   * @memberof CreatePostDto
   */
  description: string;
  /**
   * Categories
   * @type {string}
   * @memberof CreatePostDto
   */
  categories: string;
  /**
   * Image url
   * @type {string}
   * @memberof CreatePostDto
   */
  image: string;
  /**
   * Author name
   * @type {string}
   * @memberof CreatePostDto
   */
  author: string;
}

/**
 * Check if a given object implements the CreatePostDto interface.
 */
export function instanceOfCreatePostDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "description" in value;
  isInstance = isInstance && "categories" in value;
  isInstance = isInstance && "image" in value;
  isInstance = isInstance && "author" in value;

  return isInstance;
}

export function CreatePostDtoFromJSON(json: any): CreatePostDto {
  return CreatePostDtoFromJSONTyped(json, false);
}

export function CreatePostDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreatePostDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json["title"],
    description: json["description"],
    categories: json["categories"],
    image: json["image"],
    author: json["author"],
  };
}

export function CreatePostDtoToJSON(value?: CreatePostDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    description: value.description,
    categories: value.categories,
    image: value.image,
    author: value.author,
  };
}
