/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
  /**
   * Email
   * @type {string}
   * @memberof CreateUserDto
   */
  email: string;
  /**
   * Password
   * @type {string}
   * @memberof CreateUserDto
   */
  password: string;
}

/**
 * Check if a given object implements the CreateUserDto interface.
 */
export function instanceOfCreateUserDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "email" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
  return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
  };
}

export function CreateUserDtoToJSON(value?: CreateUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
