/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Post
 */
export interface Post {
  /**
   * Unique identificator
   * @type {number}
   * @memberof Post
   */
  id: number;
  /**
   * Post title
   * @type {string}
   * @memberof Post
   */
  title: string;
  /**
   * Post description
   * @type {string}
   * @memberof Post
   */
  description: string;
  /**
   * Post categories
   * @type {Array<string>}
   * @memberof Post
   */
  categories: Array<string>;
  /**
   * Main post image
   * @type {string}
   * @memberof Post
   */
  image: string;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "description" in value;
  isInstance = isInstance && "categories" in value;
  isInstance = isInstance && "image" in value;

  return isInstance;
}

export function PostFromJSON(json: any): Post {
  return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Post {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    description: json["description"],
    categories: json["categories"],
    image: json["image"],
  };
}

export function PostToJSON(value?: Post | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    description: value.description,
    categories: value.categories,
    image: value.image,
  };
}
