/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ResponsePostDto
 */
export interface ResponsePostDto {
  /**
   * Total count
   * @type {number}
   * @memberof ResponsePostDto
   */
  count: number;
  /**
   * Post list
   * @type {Array<string>}
   * @memberof ResponsePostDto
   */
  rows: Array<string>;
}

/**
 * Check if a given object implements the ResponsePostDto interface.
 */
export function instanceOfResponsePostDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "count" in value;
  isInstance = isInstance && "rows" in value;

  return isInstance;
}

export function ResponsePostDtoFromJSON(json: any): ResponsePostDto {
  return ResponsePostDtoFromJSONTyped(json, false);
}

export function ResponsePostDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsePostDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    count: json["count"],
    rows: json["rows"],
  };
}

export function ResponsePostDtoToJSON(value?: ResponsePostDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    count: value.count,
    rows: value.rows,
  };
}
