/* tslint:disable */
/* eslint-disable */
/**
 * Rss-back
 * Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ResponseLoginDto
 */
export interface ResponseLoginDto {
  /**
   * Jwt token
   * @type {string}
   * @memberof ResponseLoginDto
   */
  token: string;
}

/**
 * Check if a given object implements the ResponseLoginDto interface.
 */
export function instanceOfResponseLoginDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "token" in value;

  return isInstance;
}

export function ResponseLoginDtoFromJSON(json: any): ResponseLoginDto {
  return ResponseLoginDtoFromJSONTyped(json, false);
}

export function ResponseLoginDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponseLoginDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    token: json["token"],
  };
}

export function ResponseLoginDtoToJSON(value?: ResponseLoginDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    token: value.token,
  };
}
